from __future__ import annotations

"""Run the complete publication suite from scratch and publish flat artifacts.

The scientific drivers work in a temporary directory so the repository remains clean.
At the end of each stage, publication-facing tables/summaries/logs are copied directly
into ``outputs/`` and every PNG/PDF/GIF is copied into the single flat
``outputs/figures/`` directory. Large transient states used only to connect stages are
not published; they are regenerated by this command whenever needed.
"""

import argparse
import csv
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parent
OUTPUT_ROOT = REPO_ROOT / "outputs"
FIGURE_ROOT = OUTPUT_ROOT / "figures"
CACHE_ROOT = REPO_ROOT / "cache"

TEXT_EXTENSIONS = {".csv", ".json", ".txt", ".yaml", ".yml"}
VISUAL_EXTENSIONS = {".png", ".pdf", ".gif"}
SKIP_NAMES = {"final_state.npz"}


@dataclass
class StageResult:
    index: int
    stage_id: str
    description: str
    command: str
    status: str
    returncode: Optional[int]
    elapsed_s: float
    log_file: str
    published_artifacts: int = 0


def _display_command(parts: Sequence[str]) -> str:
    if os.name == "nt":
        return subprocess.list2cmdline(list(parts))
    return " ".join(shlex.quote(str(p)) for p in parts)


def _safe_flat_name(stage_id: str, relative: Path) -> str:
    pieces = [stage_id, *relative.parts]
    return "__".join(piece.replace(" ", "_") for piece in pieces)


def _reset_outputs(clear_cache: bool) -> None:
    if OUTPUT_ROOT.exists():
        shutil.rmtree(OUTPUT_ROOT)
    FIGURE_ROOT.mkdir(parents=True, exist_ok=True)
    (OUTPUT_ROOT / ".gitkeep").write_text("", encoding="utf-8")
    (FIGURE_ROOT / ".gitkeep").write_text("", encoding="utf-8")
    if clear_cache and CACHE_ROOT.exists():
        shutil.rmtree(CACHE_ROOT)


def _publish_tree(stage_id: str, source_root: Path, index_rows: list[dict]) -> int:
    if not source_root.exists():
        return 0
    count = 0
    for source in sorted(p for p in source_root.rglob("*") if p.is_file()):
        if source.name in SKIP_NAMES or source.name.startswith("state_") and source.suffix.lower() == ".npz":
            continue
        suffix = source.suffix.lower()
        if suffix in VISUAL_EXTENSIONS:
            dest_root = FIGURE_ROOT
        elif suffix in TEXT_EXTENSIONS:
            dest_root = OUTPUT_ROOT
        else:
            continue
        relative = source.relative_to(source_root)
        dest = dest_root / _safe_flat_name(stage_id, relative)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, dest)
        index_rows.append({
            "stage": stage_id,
            "source_relative": str(relative).replace("\\", "/"),
            "published": str(dest.relative_to(REPO_ROOT)).replace("\\", "/"),
        })
        count += 1
    return count


def _write_json(path: Path, obj) -> None:
    path.write_text(json.dumps(obj, indent=2, allow_nan=True), encoding="utf-8")


def _write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", encoding="utf-8-sig", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def _run_stage(
    *,
    index: int,
    stage_id: str,
    description: str,
    command: Sequence[str],
    artifact_root: Optional[Path],
    env: dict[str, str],
    dry_run: bool,
    artifact_index: list[dict],
) -> StageResult:
    command_text = _display_command(command)
    log_file = OUTPUT_ROOT / f"{index:02d}_{stage_id}.log"
    print("\n" + "=" * 112)
    print(f"[SUITE {index:02d}] {stage_id}: {description}")
    print(f"[COMMAND] {command_text}")
    print("=" * 112)

    if dry_run:
        log_file.write_text(f"DRY RUN\n{command_text}\n", encoding="utf-8")
        return StageResult(index, stage_id, description, command_text, "dry_run", None, 0.0, str(log_file))

    t0 = time.perf_counter()
    merged_env = os.environ.copy()
    merged_env.update(env)
    with log_file.open("w", encoding="utf-8", errors="replace") as log:
        log.write(f"COMMAND: {command_text}\n\n")
        proc = subprocess.Popen(
            list(command),
            cwd=REPO_ROOT,
            env=merged_env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
        )
        assert proc.stdout is not None
        for line in proc.stdout:
            print(line, end="")
            log.write(line)
        rc = proc.wait()
    elapsed = time.perf_counter() - t0
    status = "passed" if rc == 0 else "failed"
    published = _publish_tree(stage_id, artifact_root, artifact_index) if artifact_root is not None else 0
    print(f"[SUITE {index:02d}] {stage_id} -> {status.upper()} in {elapsed:.2f} s; published={published}")
    return StageResult(index, stage_id, description, command_text, status, rc, elapsed, str(log_file), published)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Run the complete PyDebrisFlow2D publication suite from scratch.")
    parser.add_argument("--backend", choices=("auto", "cpu", "cuda"), default="auto")
    parser.add_argument("--fresh", action="store_true", help="Delete old outputs and the DEM cache before the run.")
    parser.add_argument("--smoke", action="store_true", help="Short wiring run, not publication evidence.")
    parser.add_argument("--skip-performance", action="store_true", help="Skip only the CPU/CUDA benchmark.")
    parser.add_argument("--dry-run", action="store_true", help="Print the commands without running simulations.")
    parser.add_argument("--fail-fast", action="store_true", help="Stop after the first failed stage.")
    args = parser.parse_args(argv)

    if args.fresh:
        _reset_outputs(clear_cache=True)
    else:
        FIGURE_ROOT.mkdir(parents=True, exist_ok=True)

    backend = args.backend
    py = sys.executable
    env = {
        "NUMBA_CUDA_LOW_OCCUPANCY_WARNINGS": "0",
        "PYTHONUTF8": "1",
        "PYTHONIOENCODING": "utf-8",
    }
    t_end = 2.0 if args.smoke else 275.0
    oj_t_end = 1.0 if args.smoke else 20.0
    perf_t_end = 1.0 if args.smoke else 20.0
    grid_spacings = [20.0, 10.0, 5.0] if args.smoke else [20.0, 15.0, 10.0, 8.0, 6.5, 5.0]
    cfl_values = [0.10, 0.075] if args.smoke else [0.25, 0.15, 0.10, 0.075]

    artifact_index: list[dict] = []
    results: list[StageResult] = []

    with tempfile.TemporaryDirectory(prefix="pydebrisflow_suite_") as td:
        work = Path(td)
        core_root = work / "core"
        concentration_root = work / "concentration"
        ablation_root = work / "ablation"
        grid_root = work / "grid"
        reviewer_root = work / "reviewer"
        cfl_root = work / "cfl"
        oj_root = work / "oj_end_to_end"
        perf_root = work / "performance"
        hydro_state = grid_root / "runs" / "dx5m_O2" / "final_state.npz"

        stages: list[tuple[str, str, list[str], Optional[Path]]] = [
            (
                "regression_reviewer",
                "Lightweight reviewer/GCI/bottleneck regression checks",
                [py, str(REPO_ROOT / "tests" / "test_reviewer_regression.py")],
                None,
            ),
            (
                "regression_cfl",
                "CFL summary-driver regression checks",
                [py, str(REPO_ROOT / "tests" / "test_cfl_regression.py")],
                None,
            ),
            (
                "regression_concentration_rheology",
                "Continuous concentration-aware O'Brien-Julien regression checks",
                [py, str(REPO_ROOT / "tests" / "test_concentration_rheology.py")],
                None,
            ),
            (
                "regression_windows_console",
                "Windows redirected-console encoding regression check",
                [py, str(REPO_ROOT / "tests" / "test_windows_console_compat.py")],
                None,
            ),
            (
                "concentration_sweep",
                "Dense solid-concentration sweep for continuity and monotonicity",
                [
                    py, str(REPO_ROOT / "tests" / "test_concentration_sweep.py"),
                    "--config", str(REPO_ROOT / "configs" / "obrien_julien_quick.yaml"),
                    "--output-root", str(concentration_root),
                ],
                concentration_root,
            ),
            (
                "core_verification",
                "Controlled numerical verification and Ritter accuracy/cost products",
                [
                    py, str(REPO_ROOT / "verify_core.py"),
                    "--config", str(REPO_ROOT / "configs" / "verification.yaml"),
                    "--marsicano-config", str(REPO_ROOT / "configs" / "marsicano_voellmy.yaml"),
                    "--backend", backend,
                    "--output-dir", str(core_root),
                ],
                core_root,
            ),
        ]

        ablation_cmd = [
            py, str(REPO_ROOT / "run_marsicano_studies.py"),
            "--config", str(REPO_ROOT / "configs" / "marsicano_multiphysics.yaml"),
            "--backend", backend,
            "--output-root", str(ablation_root),
            "--no-resume",
            "--overwrite-png",
        ]
        if args.smoke:
            ablation_cmd += ["--t-end", f"{t_end:g}", "--orders", "O2", "--cases", "P000", "EDS111"]
        stages.append(("marsicano_ablation", "Voellmy Marsicano 2x8 multiphysics ablation matrix", ablation_cmd, ablation_root))

        grid_cmd = [
            py, str(REPO_ROOT / "run_marsicano_studies.py"),
            "--config", str(REPO_ROOT / "configs" / "marsicano_multiphysics.yaml"),
            "--grid-sensitivity-only",
            "--backend", backend,
            "--grid-spacings", *[f"{v:g}" for v in grid_spacings],
            "--grid-cfl", "0.10",
            "--grid-output-root", str(grid_root),
            "--t-end", f"{t_end:g}",
            "--no-resume",
            "--overwrite-png",
        ]
        stages.append(("grid_study", "Real-topography Marsicano grid/GCI/bottleneck study", grid_cmd, grid_root))

        review_cmd = [
            py, str(REPO_ROOT / "run_reviewer_diagnostics.py"),
            "--all",
            "--config", str(REPO_ROOT / "configs" / "marsicano_multiphysics.yaml"),
            "--output-root", str(reviewer_root),
            "--backend", backend,
            "--grid-spacing", "20",
            "--t-end", f"{t_end:g}",
            "--hydrostatic-state", str(hydro_state),
            "--wet-threshold", "0.01",
            "--curvature-sigma", "1.0",
            "--no-resume",
        ]
        stages.append(("reviewer_diagnostics", "Five reviewer-requested physical and sensitivity diagnostics", review_cmd, reviewer_root))

        cfl_cmd = [
            py, str(REPO_ROOT / "run_cfl_study.py"),
            "--config", str(REPO_ROOT / "configs" / "marsicano_multiphysics.yaml"),
            "--backend", backend,
            "--cfl-values", *[f"{v:g}" for v in cfl_values],
            "--dx", "5",
            "--t-end", f"{t_end:g}",
            "--output-root", str(cfl_root),
            "--force",
        ]
        stages.append(("cfl_stability", "Native-5 m temporal robustness study", cfl_cmd, cfl_root))

        oj_cmd = [
            py, str(REPO_ROOT / "tests" / "test_oj_end_to_end.py"),
            "--config", str(REPO_ROOT / "configs" / "obrien_julien_quick.yaml"),
            "--backend", backend,
            "--output-root", str(oj_root),
            "--t-end", f"{oj_t_end:g}",
        ]
        stages.append(("obrien_julien_end_to_end", "Short real-DEM integration check for the alternative O'Brien-Julien closure", oj_cmd, oj_root))

        if not args.skip_performance:
            perf_cmd = [
                py, str(REPO_ROOT / "tests" / "test_cpu_cuda_benchmark.py"),
                "--config", str(REPO_ROOT / "configs" / "marsicano_voellmy.yaml"),
                "--dx", "20", "10", "5",
                "--t-end", f"{perf_t_end:g}",
                "--order", "2",
                "--out-dir", str(perf_root),
            ]
            stages.append(("cpu_cuda_benchmark", "Matched CPU/CUDA runtime and memory benchmark", perf_cmd, perf_root))

        commands = [
            {"index": i, "stage": sid, "command": _display_command(cmd)}
            for i, (sid, _, cmd, _) in enumerate(stages, start=1)
        ]
        _write_json(OUTPUT_ROOT / "suite_commands.json", commands)

        print("\nPyDebrisFlow2D FULL PUBLICATION SUITE")
        print(f"Backend: {backend}")
        print(f"Fresh run: {bool(args.fresh)}")
        print(f"Smoke profile: {bool(args.smoke)}")
        print(f"Final data directory: {OUTPUT_ROOT}")
        print(f"Final figure directory: {FIGURE_ROOT}")
        print(f"Number of stages: {len(stages)}")

        for index, (stage_id, description, command, artifact_root) in enumerate(stages, start=1):
            if stage_id == "reviewer_diagnostics" and not args.dry_run and not hydro_state.is_file():
                log_file = OUTPUT_ROOT / f"{index:02d}_{stage_id}.log"
                note = f"Required 5 m grid state missing: {hydro_state}"
                log_file.write_text(note + "\n", encoding="utf-8")
                result = StageResult(index, stage_id, description, _display_command(command), "skipped_dependency", None, 0.0, str(log_file), 0)
            else:
                result = _run_stage(
                    index=index,
                    stage_id=stage_id,
                    description=description,
                    command=command,
                    artifact_root=artifact_root,
                    env=env,
                    dry_run=args.dry_run,
                    artifact_index=artifact_index,
                )
            results.append(result)
            _write_json(OUTPUT_ROOT / "suite_summary.json", [asdict(r) for r in results])
            _write_csv(OUTPUT_ROOT / "suite_summary.csv", [asdict(r) for r in results])
            _write_csv(OUTPUT_ROOT / "artifact_index.csv", artifact_index)
            if result.status in {"failed", "skipped_dependency"} and args.fail_fast:
                break

    failed = [r for r in results if r.status in {"failed", "skipped_dependency"}]
    manifest = {
        "software": "PyDebrisFlow2D",
        "version": "1.4.0",
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "backend": backend,
        "fresh": bool(args.fresh),
        "smoke": bool(args.smoke),
        "stage_count": len(results),
        "passed": sum(r.status == "passed" for r in results),
        "failed_or_skipped": len(failed),
        "output_layout": {
            "data_logs_and_summaries": "outputs/ (flat)",
            "all_figures": "outputs/figures/ (flat)",
        },
        "rheology_policy": {
            "marsicano_publication_baseline": "Voellmy",
            "alternative_concentration_aware_closure": "O'Brien-Julien continuous_asymptotic",
            "closures_are_alternatives_not_summed": True,
        },
        "results": [asdict(r) for r in results],
        "artifact_count": len(artifact_index),
    }
    _write_json(OUTPUT_ROOT / "publication_manifest.json", manifest)

    print("\n" + "=" * 112)
    print("FINAL SUITE SUMMARY")
    print("=" * 112)
    for r in results:
        print(f"{r.index:02d}  {r.stage_id:<32s} {r.status:<20s} {r.elapsed_s:>10.2f} s  artifacts={r.published_artifacts}")
    print(f"Data/logs: {OUTPUT_ROOT}")
    print(f"Figures:   {FIGURE_ROOT}")
    print(f"Manifest:  {OUTPUT_ROOT / 'publication_manifest.json'}")

    if args.dry_run:
        return 0
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
